# Artificial Neural Network

### Importing the libraries

In [111]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

## Part 1 - Data Preprocessing

### Importing the dataset

In [53]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [54]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [55]:
dataset.iloc[:,3:-1]

CreditScore Geography  Gender  Age  ...  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France  Female   42  ...              1          1               1        101348.88
1             608     Spain  Female   41  ...              1          0               1        112542.58
2             502    France  Female   42  ...              3          1               0        113931.57
3             699    France  Female   39  ...              2          0               0         93826.63
4             850     Spain  Female   43  ...              1          1               1         79084.10
...           ...       ...     ...  ...  ...            ...        ...             ...              ...
9995          771    France    Male   39  ...              2          1               0         96270.64
9996          516    France    Male   35  ...              1          1               1        101699.77
9997          709    France  Female   36  ...              1          0               1         42085.58
9998          772   Germany    Male   42  ...              2          1               0         92888.52
9999          792    France  Female   28  ...              1          1               0         38190.78

[10000 rows x 10 columns]

### Encoding categorical data

Label Encoding the "Gender" column

In [56]:
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [57]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder="passthrough")
X = ct.fit_transform(X)
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature Scaling

In [59]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [65]:
ann = Sequential()

### Adding the input layer and the first hidden layer

In [66]:
ann.add(Dense(6, 'relu'))

### Adding the second hidden layer

In [67]:
ann.add(Dense(6, 'relu'))

### Adding the output layer

In [68]:
ann.add(Dense(1, 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [70]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training set

In [72]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4700 - accuracy: 0.7995
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4448 - accuracy: 0.8090
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4370 - accuracy: 0.8101
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4335 - accuracy: 0.8119
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4301 - accuracy: 0.8130
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4273 - accuracy: 0.8123
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4241 - accuracy: 0.8154
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4216 - accuracy: 0.8180
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4187 - accuracy: 0.8185
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4155 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [104]:
customer = np.array([600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000])
customer = customer.reshape(1, len(customer))
customer[0, 2] = le.transform([customer[0, 2]])[0]
customer = ct.transform(customer)
customer

array([['1.0', '0.0', '0.0', '600', '1', '40', '3', '60000', '2', '1',
        '1', '50000']], dtype='<U32')

In [105]:
customer = sc.transform(customer)
customer

array([[ 0.98560362, -0.5698444 , -0.57369368, -0.52111599,  0.91601335,
         0.10961719, -0.68538967, -0.2569057 ,  0.8095029 ,  0.64259497,
         0.9687384 , -0.87203322]])

In [106]:
pred = ann.predict(customer)
pred

1/1 [==============================] - 0s 23ms/step


array([[0.03237496]], dtype=float32)

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [109]:
y_pred = ann.predict(X_test)
y_pred = y_pred.reshape(len(y_pred), 1)
y_pred = y_pred >= 0.5
compare = pd.concat([pd.DataFrame(y_pred, columns=["Prediction"]), pd.DataFrame(y_test.reshape(len(y_test), 1), columns=["Original"])], 1)
compare.iloc[:30,:]

63/63 [==============================] - 0s 4ms/step


<ipython-input-109-5214820e23e9>:4: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only.
  compare = pd.concat([pd.DataFrame(y_pred, columns=["Prediction"]), pd.DataFrame(y_test.reshape(len(y_test), 1), columns=["Original"])], 1)


Prediction  Original
0        False         0
1        False         1
2        False         0
3        False         0
4        False         0
5         True         1
6        False         0
7        False         0
8        False         1
9         True         1
10       False         0
11       False         0
12       False         0
13       False         0
14        True         1
15       False         1
16       False         0
17       False         0
18       False         0
19       False         0
20        True         0
21       False         0
22       False         0
23       False         0
24       False         0
25       False         0
26       False         0
27       False         0
28       False         0
29       False         0

### Making the Confusion Matrix

In [115]:
cm = confusion_matrix(y_pred, y_test)
acc = accuracy_score(y_pred, y_test)
print(cm)
print(f'Accuracy Score: {acc*100}%')

[[1532  215]
 [  63  190]]
Accuracy Score: 86.1%
